/// Generates a complete, compilable Flutter project from a [ProjectModel].
///
/// This orchestrates the [WidgetMapper] and [DartGenerator] to produce a set
/// of source files (main.dart, pages, widgets, models, services, state) that
/// form a standalone Flutter app.
library;

import '../../domain/project_model.dart';
import '../../domain/ui_node.dart';
import '../../domain/widget_model.dart';
import '../mapping/widget_mapper.dart';
import 'dart_generator.dart';
import 'backend/backend_generator.dart';

/// A generated source file with its relative path and content.
class GeneratedFile {
  GeneratedFile({required this.path, required this.content});
  final String path;
  final String content;
}

/// Result of generating a project.
class GenerationResult {
  GenerationResult({required this.files, this.warnings = const []});
  final List<GeneratedFile> files;
  final List<String> warnings;
}

class ProjectGenerator {
  ProjectGenerator({
    WidgetMapper? mapper,
    DartGenerator? dartGen,
  })  : _mapper = mapper ?? WidgetMapper(),
        _dartGen = dartGen ?? DartGenerator();

  final WidgetMapper _mapper;
  final DartGenerator _dartGen;

  /// Generate all files for the given [project].
  GenerationResult generate(ProjectModel project) {
    final warnings = <String>[];
    final files = <GeneratedFile>[];
    final projectName = project.generatorSettings.projectName;

    // pubspec.yaml
    files.add(GeneratedFile(
      path: 'pubspec.yaml',
      content: _pubspec(project),
    ));

    // analysis_options.yaml
    files.add(GeneratedFile(
      path: 'analysis_options.yaml',
      content: _analysisOptions(),
    ));

    // main.dart
    files.add(GeneratedFile(
      path: 'lib/main.dart',
      content: _mainDart(project),
    ));

    // app/app.dart
    files.add(GeneratedFile(
      path: 'lib/app/app.dart',
      content: _appDart(project),
    ));

    // app/theme.dart
    files.add(GeneratedFile(
      path: 'lib/app/theme.dart',
      content: _themeDart(project),
    ));

    // app/router.dart
    files.add(GeneratedFile(
      path: 'lib/app/router.dart',
      content: _routerDart(project),
    ));

    // Pages
    for (final page in project.pages) {
      final fileName = _toSnakeCase(page.name);
      files.add(GeneratedFile(
        path: 'lib/pages/${fileName}_page.dart',
        content: _pageDart(page),
      ));
    }

    // Data models
    for (final model in project.dataModels) {
      files.add(GeneratedFile(
        path: 'lib/models/${_toSnakeCase(model.name)}.dart',
        content: _modelDart(model),
      ));
    }

    // API service (if any API configs)
    if (project.apiConfigs.isNotEmpty) {
      files.add(GeneratedFile(
        path: 'lib/services/api_service.dart',
        content: _apiService(project),
      ));
    }

    // State (if any variables)
    if (project.variables.isNotEmpty) {
      files.add(GeneratedFile(
        path: 'lib/state/app_state.dart',
        content: _appState(project),
      ));
    }

    // README
    files.add(GeneratedFile(
      path: 'README.md',
      content: _readme(projectName, project),
    ));

    // Assets directories
    files.add(GeneratedFile(
      path: 'assets/images/.gitkeep',
      content: '',
    ));
    files.add(GeneratedFile(
      path: 'assets/icons/.gitkeep',
      content: '',
    ));

    // Backend (if enabled)
    if (project.generatorSettings.generateBackend) {
      final backendResult = BackendGenerator().generate(
        project.generatorSettings,
        dataModels: project.dataModels,
      );
      files.addAll(backendResult.files);
    }

    return GenerationResult(files: files, warnings: warnings);
  }

  // --- File templates ---

  String _pubspec(ProjectModel project) {
    final deps = <String>['  flutter:\n    sdk: flutter'];
    if (project.apiConfigs.isNotEmpty) {
      deps.add("  http: ^1.2.1");
    }
    if (project.generatorSettings.enableCharts) {
      deps.add("  fl_chart: ^0.68.0");
    }
    final buf = StringBuffer();
    buf.writeln('name: ${project.generatorSettings.projectName}');
    buf.writeln('description: Generated by Figma Flutter App Builder');
    buf.writeln('publish_to: \'none\'');
    buf.writeln('version: 1.0.0+1');
    buf.writeln();
    buf.writeln('environment:');
    buf.writeln('  sdk: \'>=3.3.0 <4.0.0\'');
    buf.writeln('  flutter: \'>=3.19.0\'');
    buf.writeln();
    buf.writeln('dependencies:');
    for (final d in deps) {
      buf.writeln('  $d');
    }
    buf.writeln();
    buf.writeln('dev_dependencies:');
    buf.writeln('  flutter_test:');
    buf.writeln('    sdk: flutter');
    buf.writeln('  flutter_lints: ^4.0.0');
    buf.writeln();
    buf.writeln('flutter:');
    buf.writeln('  uses-material-design: true');
    buf.writeln('  assets:');
    buf.writeln('    - assets/images/');
    buf.writeln('    - assets/icons/');
    return buf.toString();
  }

  String _analysisOptions() {
    return 'include: package:flutter_lints/flutter.yaml\n';
  }

  String _mainDart(ProjectModel project) {
    final homeRoute = project.pages.firstWhere(
      (p) => p.isHome,
      orElse: () => project.pages.first,
    );
    final homeClass = _toPascalCase(homeRoute.name) + 'Page';
    return '''import 'package:flutter/material.dart';
import 'app/app.dart';

void main() {
  runApp(const ${_toPascalCase(project.generatorSettings.projectName)}App());
}
''';
  }

  String _appDart(ProjectModel project) {
    final appName = _toPascalCase(project.generatorSettings.projectName);
    final homeRoute = project.pages.firstWhere(
      (p) => p.isHome,
      orElse: () => project.pages.first,
    );
    final homeClass = _toPascalCase(homeRoute.name) + 'Page';
    return '''import 'package:flutter/material.dart';
import '../pages/${_toSnakeCase(homeRoute.name)}_page.dart';
import 'theme.dart';

class ${appName}App extends StatelessWidget {
  const ${appName}App({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: '${project.name}',
      theme: appTheme,
      home: const $homeClass(),
      debugShowCheckedModeBanner: false,
    );
  }
}
''';
  }

  String _themeDart(ProjectModel project) {
    final ds = project.designSystem;
    final buf = StringBuffer();
    buf.writeln("import 'package:flutter/material.dart';");
    buf.writeln();
    buf.writeln('ThemeData get appTheme {');
    buf.writeln('  return ThemeData(');
    buf.writeln('    colorScheme: ColorScheme.fromSeed(');
    buf.writeln('      seedColor: ${_seedColor(ds)},');
    buf.writeln('    ),');
    buf.writeln('    useMaterial3: true,');
    buf.writeln('  );');
    buf.writeln('}');
    return buf.toString();
  }

  String _seedColor(DesignSystem ds) {
    if (ds.colors.containsKey('Primary')) {
      final hex = ds.colors['Primary'] as String;
      return _colorFromHex(hex);
    }
    return 'Colors.blue';
  }

  String _colorFromHex(String hex) {
    var h = hex.replaceAll('#', '');
    if (h.length == 6) h = 'FF$h';
    return 'const Color(0x$h)';
  }

  String _routerDart(ProjectModel project) {
    final buf = StringBuffer();
    buf.writeln("import 'package:flutter/material.dart';");
    for (final page in project.pages) {
      buf.writeln("import '../pages/${_toSnakeCase(page.name)}_page.dart';");
    }
    buf.writeln();
    buf.writeln('Route<dynamic>? onGenerateRoute(RouteSettings settings) {');
    buf.writeln('  switch (settings.name) {');
    for (final page in project.pages) {
      final className = _toPascalCase(page.name) + 'Page';
      final route = page.isHome ? '/' : '/${_toSnakeCase(page.name)}';
      buf.writeln("    case '$route':");
      buf.writeln('      return MaterialPageRoute(');
      buf.writeln('        builder: (_) => const $className(),');
      buf.writeln('      );');
    }
    buf.writeln('  }');
    buf.writeln('  return null;');
    buf.writeln('}');
    return buf.toString();
  }

  String _pageDart(ProjectPage page) {
    final className = _toPascalCase(page.name) + 'Page';
    final widget = _mapper.map(page.root);
    final widgetCode = _dartGen.renderWidget(widget, indent: 3);
    return '''import 'package:flutter/material.dart';

class $className extends StatelessWidget {
  const $className({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: $widgetCode
      ),
    );
  }
}
''';
  }

  String _modelDart(DataModel model) {
    final buf = StringBuffer();
    buf.writeln("import 'package:flutter/material.dart';");
    buf.writeln();
    buf.writeln('class ${model.name} {');
    buf.writeln('  const ${model.name}({');
    for (final f in model.fields) {
      buf.writeln('    required this.${f.name},');
    }
    buf.writeln('  });');
    buf.writeln();
    for (final f in model.fields) {
      final nullable = f.nullable ? '?' : '';
      buf.writeln('  final ${f.type}$nullable ${f.name};');
    }
    buf.writeln();
    buf.writeln('  factory ${model.name}.fromJson(Map<String, dynamic> json) => ${model.name}(');
    for (final f in model.fields) {
      buf.writeln('    ${f.name}: json[\'${f.name}\'] as ${f.type}${f.nullable ? '?' : ''},');
    }
    buf.writeln('  );');
    buf.writeln();
    buf.writeln('  Map<String, dynamic> toJson() => {');
    for (final f in model.fields) {
      buf.writeln("    '${f.name}': ${f.name},");
    }
    buf.writeln('  };');
    buf.writeln('}');
    return buf.toString();
  }

  String _apiService(ProjectModel project) {
    final buf = StringBuffer();
    buf.writeln("import 'dart:convert';");
    buf.writeln("import 'package:http/http.dart' as http;");
    buf.writeln();
    buf.writeln('class ApiService {');
    buf.writeln('  ApiService({this.baseUrl = \'https://api.example.com\'});');
    buf.writeln('  final String baseUrl;');
    buf.writeln();
    for (final cfg in project.apiConfigs) {
      buf.writeln('  Future<dynamic> ${_toCamelCase(cfg.name)}() async {');
      buf.writeln('    final uri = Uri.parse(\'\$baseUrl${cfg.url}\');');
      buf.writeln('    final response = await http.${cfg.method.toLowerCase()}(uri);');
      buf.writeln('    if (response.statusCode != 200) {');
      buf.writeln('      throw Exception(\'API error: \${response.statusCode}\');');
      buf.writeln('    }');
      buf.writeln('    return jsonDecode(response.body);');
      buf.writeln('  }');
      buf.writeln();
    }
    buf.writeln('}');
    return buf.toString();
  }

  String _appState(ProjectModel project) {
    final buf = StringBuffer();
    buf.writeln('// App-level state variables');
    buf.writeln();
    for (final v in project.variables) {
      buf.writeln('dynamic ${v.name} = ${_defaultForType(v.type)};');
    }
    return buf.toString();
  }

  String _defaultForType(String type) {
    return switch (type) {
      'String' => "''",
      'int' => '0',
      'double' => '0.0',
      'bool' => 'false',
      'List' => 'const []',
      'Map' => 'const {}',
      _ => 'null',
    };
  }

  String _readme(String projectName, ProjectModel project) {
    return '''# $projectName

Generated by **Figma Flutter App Builder**.

## Getting Started

```bash
flutter pub get
flutter run
```

## Structure

- `lib/main.dart` – Entry point
- `lib/app/` – App, theme, router
- `lib/pages/` – Screen pages
- `lib/models/` – Data models
- `lib/services/` – API services
- `lib/state/` – App state

## Pages

${project.pages.map((p) => '- ${p.name}${p.isHome ? ' (home)' : ''}').join('\n')}
''';
  }

  // --- String helpers ---

  String _toSnakeCase(String input) {
    return input
        .replaceAll(RegExp(r'[^a-zA-Z0-9]'), '_')
        .replaceAllMapped(RegExp(r'([A-Z])'), (m) => '_${m[1]!.toLowerCase()}')
        .replaceAll(RegExp(r'_+'), '_')
        .toLowerCase()
        .replaceFirst(RegExp(r'^_'), '');
  }

  String _toPascalCase(String input) {
    final parts = input
        .replaceAll(RegExp(r'[^a-zA-Z0-9]'), ' ')
        .split(RegExp(r'\s+'))
        .where((s) => s.isNotEmpty);
    return parts.map((p) {
      if (p.isEmpty) return '';
      return p[0].toUpperCase() + p.substring(1).toLowerCase();
    }).join('');
  }

  String _toCamelCase(String input) {
    final pascal = _toPascalCase(input);
    if (pascal.isEmpty) return input;
    return pascal[0].toLowerCase() + pascal.substring(1);
  }
}
